### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by reiven** [vkobel/ethereum-generate-wallet#1]
Hi! 

I'm trying to use your python script, but the sha3 module looks like do not have the keccak_256() module. I've created a new python3 virtualenv, installed sha3 and ecdsa (maybe it will be a good idea to include a requirements.txt in your repo, i can to that if its for you) with the following version:
``` pip freeze
ecdsa==0.13
sha3==0.2.1
```

How can i make the script work?

Thanks

**Comment by reiven** [comment]
Sorry, i didnt notice that the correct module neede is pysha3.
Anyway, it will be a good idea to include a requirements.txt file for python

**Comment by vkobel** [comment]
Adding requirements.txt sounds like a good idea. I would be happy to accept your pull request 😎

**Comment by reiven** [comment]
ok!

**Comment by vkobel** [comment]
Thanks!
