### ISSUE TITLE
hex() cannot be used on an string variable

### ISSUE THREAD

**Issue by Ronserruya** [vkobel/ethereum-generate-wallet#10]
Whenever I run this, I get an error while printing the keys 
"AttributeError: 'str' object has no attribute 'hex'"

I was able to fix this by changing 
"to_string().hex()" to "to_string().encode('hex')

wonder if there is anything that I missed, or is this just something that needs to be fixed.
python 2.7.12 if it matters

**Comment by vkobel** [comment]
Hi, your issue is purely related to your python version. The code here runs on python3. I will update the shebang accordingly.
