### ISSUE TITLE
Python error: no attribute 'keccak_256'

### ISSUE THREAD

**Issue by waynemystir** [vkobel/ethereum-generate-wallet#3]
I run this:

pip install -r requirements.txt

And I get this:

Requirement already satisfied: ecdsa in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: pysha3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))

But I get an error when I run it:

./ethereum-wallet-generator.py

Traceback (most recent call last):
  File "./ethereum-wallet-generator.py", line 9, in <module>
    keccak = sha3.keccak_256()
AttributeError: 'module' object has no attribute 'keccak_256'

**Comment by vkobel** [comment]
Commit 9360c060780a0aed264bec09673641c205495517 should fix this issue.
I guess you don't have pysha3 latest version.
Does it works now?
