### ISSUE TITLE
Missing keccak-256sum

### ISSUE THREAD

**Issue by bibz0r** [vkobel/ethereum-generate-wallet#5]
Hey,

I'm getting this error:

./ethereum-wallet-generator.sh: 12: ./ethereum-wallet-generator.sh: keccak-256sum: not found

But I've already done pip install requirements.txt

newest debian x64 running

**Comment by bibz0r** [comment]
Oh, seems like I was once again too quick with creating a ticket.. Just saw/understood that I'm missing the keccak-256sum executable, but you were so kind and put the binaries in /lib/

Specifing the absolute path in the bash script helped. I will create a pull request with a built-in architecture check.

**Comment by vkobel** [comment]
Thanks @bibz0r 🥇 !
